"""
ml/risk_scorer.py
Loads seasonal predictions generated by the Prophet notebook.
Used by the WhatsApp bot and scan router.
"""
import json
import os
from datetime import datetime

# Try to load predictions from notebook output
_predictions = {}
_PRED_FILE = os.path.join(os.path.dirname(__file__), 'seasonal_predictions.json')

try:
    with open(_PRED_FILE, 'r') as f:
        _predictions = json.load(f)
    print(f"✅ Loaded seasonal predictions for {len(_predictions)} food categories")
except FileNotFoundError:
    print("⚠ seasonal_predictions.json not found — using fallback risk scorer")

# Fallback static seasonal risk (when notebook hasn't been run)
_FALLBACK = {
    'turmeric':    {3: 'HIGH', 4: 'HIGH', 10: 'MEDIUM', 11: 'HIGH'},
    'milk':        {5: 'HIGH', 6: 'HIGH', 7: 'HIGH', 8: 'MEDIUM'},
    'honey':       {10: 'MEDIUM', 11: 'HIGH', 12: 'HIGH', 1: 'MEDIUM'},
    'ghee':        {10: 'HIGH', 11: 'CRITICAL', 12: 'HIGH'},
    'mustard_oil': {1: 'MEDIUM', 2: 'MEDIUM', 11: 'MEDIUM', 12: 'MEDIUM'},
    'paneer':      {10: 'HIGH', 11: 'HIGH', 3: 'MEDIUM', 4: 'MEDIUM'},
}

_NAME_MAP = {
    'haldi': 'turmeric', 'हल्दी': 'turmeric', 'हळद': 'turmeric',
    'doodh': 'milk', 'दूध': 'milk',
    'shahad': 'honey', 'मध': 'honey', 'शहद': 'honey',
    'tup': 'ghee', 'तूप': 'ghee', 'ghee': 'ghee',
    'sarson oil': 'mustard_oil', 'mustard oil': 'mustard_oil',
    'cheese': 'paneer',
}

MONTH_NAMES = ['','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']

def predict_seasonal_risk(food_name: str, month: int = None) -> dict:
    """Returns seasonal risk prediction for a food item."""
    if month is None:
        month = datetime.now().month

    food_key = food_name.lower().strip().replace(' ', '_').replace('-', '_')
    food_key = _NAME_MAP.get(food_key, food_key)

    month_name = MONTH_NAMES[month]

    # Use Prophet predictions if available
    if _predictions and food_key in _predictions:
        month_str = str(month)
        data = _predictions[food_key].get(month_str, {})
        risk_level = data.get('risk_level', 'LOW')
        risk_score = data.get('risk_score', 20)
        return {
            "seasonal_alert": risk_level in ['HIGH', 'CRITICAL'],
            "risk_level":     risk_level,
            "risk_score":     risk_score,
            "month":          month_name,
            "source":         "prophet_model",
            "reason":         f"{food_name.title()} adulteration peaks in {month_name} — buy from FSSAI certified sources"
                              if risk_level in ['HIGH', 'CRITICAL'] else
                              f"Normal risk for {food_name.title()} in {month_name}",
        }

    # Fallback to static rules
    risk_level = _FALLBACK.get(food_key, {}).get(month, 'LOW')
    risk_score = {'CRITICAL': 90, 'HIGH': 70, 'MEDIUM': 45, 'LOW': 20}.get(risk_level, 20)

    return {
        "seasonal_alert": risk_level in ['HIGH', 'CRITICAL'],
        "risk_level":     risk_level,
        "risk_score":     risk_score,
        "month":          month_name,
        "source":         "static_fallback",
        "reason":         f"{food_name.title()} adulteration peaks in {month_name} — buy from FSSAI certified sources"
                          if risk_level in ['HIGH', 'CRITICAL'] else
                          f"Normal risk for {food_name.title()} in {month_name}",
    }
